CREATE DATABASE IF NOT EXISTS avaris CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE avaris;
CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(60) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('member','admin') NOT NULL DEFAULT 'member',
 access_expires_at DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS invites (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 code_hash CHAR(64) NOT NULL UNIQUE,
 code_hint VARCHAR(12) NOT NULL,
 label VARCHAR(80) NOT NULL,
 duration_days INT UNSIGNED NOT NULL,
 redeem_by DATETIME NOT NULL,
 created_by BIGINT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 used_by BIGINT UNSIGNED NULL,
 used_at DATETIME NULL,
 revoked_at DATETIME NULL,
 FOREIGN KEY (created_by) REFERENCES users(id),
 FOREIGN KEY (used_by) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_log (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NULL,
 action VARCHAR(190) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS rate_limits (
 bucket CHAR(64) PRIMARY KEY,
 attempts INT UNSIGNED NOT NULL DEFAULT 1,
 window_started DATETIME NOT NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS server_setups (
 user_id BIGINT UNSIGNED PRIMARY KEY,
 server_name VARCHAR(80) NOT NULL,
 framework VARCHAR(20) NOT NULL,
 screenshots TINYINT(1) NOT NULL DEFAULT 0,
 completed_steps TEXT NOT NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;
