CREATE TABLE IF NOT EXISTS server_licenses (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL UNIQUE,
 key_hash CHAR(64) NOT NULL UNIQUE,
 key_hint VARCHAR(8) NOT NULL,
 server_id CHAR(32) NOT NULL,
 bound_ip VARCHAR(45) NULL,
 activated_at DATETIME NULL,
 last_seen_at DATETIME NULL,
 rotated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 revoked_at DATETIME NULL,
 FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;
