<?php
if (!isset($user) || !$user) { http_response_code(404); exit; }
$serverSetup=null; $setupAvailable=true;
try { $serverSetup=query('SELECT * FROM server_setups WHERE user_id=?',[$user['id']])->fetch() ?: null; }
catch (PDOException $ex) { if (($ex->errorInfo[1]??0)!==1146) throw $ex; $setupAvailable=false; }
$saved=$serverSetup??['server_name'=>'','framework'=>'standalone','screenshots'=>0,'completed_steps'=>'[]','updated_at'=>null];
$completed=json_decode($saved['completed_steps'],true)?:[];
$frameworks=['standalone'=>'Standalone / custom','esx'=>'ESX Legacy','qbcore'=>'QBCore','qbox'=>'Qbox','vrp'=>'vRP'];
$cores=['standalone'=>'','esx'=>'es_extended','qbcore'=>'qb-core','qbox'=>'qbx_core','vrp'=>'vrp'];
$startup="# Merge into your existing server.cfg; keep your database and framework dependencies.\n# Enable OneSync in txAdmin or keep this setting in server.cfg.\nset onesync on\n\n";
if ($cores[$saved['framework']]) $startup.="# Keep your existing framework startup before Avaris.\nensure ".$cores[$saved['framework']]."\n";
if ($saved['screenshots']) $startup.="ensure screenshot-basic\n";
$startup.="ensure Avaris-AC\n# Avaris-AC starts its sibling Avaris-Guard automatically.\n";
$permissions="# Replace YOUR_FIVEM_LICENSE with your own identifier (without license:).\nadd_principal identifier.license:YOUR_FIVEM_LICENSE group.avaris_staff\nadd_ace group.avaris_staff avarisac.bypass allow";
$steps=['files'=>'Place your resources','config'=>'Set the startup order','staff'=>'Give yourself in-game access','diagnostics'=>'Run the in-game checks','tuning'=>'Test your real gameplay'];
$firstIncomplete=null; foreach($steps as $key=>$title) if(!in_array($key,$completed,true)) { $firstIncomplete=$key; break; }
?>
<section id="server-setup" class="server-setup">
<div class="panel setup-intro"><div><div class="eyebrow">YOUR SERVER / GUIDED INSTALLATION</div><h2><?= $saved['server_name']?e($saved['server_name']):'Let’s set up your server.' ?></h2><p>Choose your framework, follow your setup guide, and pick up where you left off.</p></div><div class="setup-progress"><strong><?= count($completed) ?><span> / 5</span></strong><small>steps you’ve confirmed</small><progress max="5" value="<?= count($completed) ?>" aria-label="Setup steps confirmed"><?= count($completed) ?> of 5</progress></div></div>
<?php if(!$setupAvailable): ?><div class="notice error" role="alert">Server setup is not enabled yet. Ask the website administrator to import server-setup.sql into the existing Avaris database.</div><?php else: ?>
<form method="post" class="panel server-profile"><?php csrf(); ?><input type="hidden" name="action" value="save_server_profile"><div class="panel-heading"><h3>01 / Your server</h3><?= badge($serverSetup?'PROFILE SAVED':'START HERE') ?></div><div class="setup-profile-fields"><label>Server name<input name="server_name" maxlength="80" required placeholder="e.g. Northside Roleplay" value="<?= e($saved['server_name']) ?>"></label><label>Framework<select name="framework"><?php foreach($frameworks as $key=>$label): ?><option value="<?= $key ?>" <?= $saved['framework']===$key?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label>Screenshot evidence<select name="screenshots"><option value="0" <?= !$saved['screenshots']?'selected':'' ?>>No / install later</option><option value="1" <?= $saved['screenshots']?'selected':'' ?>>Yes — I have screenshot-basic</option></select></label><button class="button primary" type="submit"><?= $serverSetup?'Update setup guide':'Create my setup guide' ?> ↗</button></div><p class="fine-print">Changing your framework or evidence option resets the checklist so you can check the new configuration.</p></form>
<?php if($serverSetup): ?>
<div class="setup-layout"><div><div class="setup-section-heading"><h3>02 / Install Avaris</h3><span><?= e($frameworks[$saved['framework']]) ?></span></div>
<?php foreach($steps as $key=>$title): ?>
<details class="setup-step" <?= $key===$firstIncomplete?'open':'' ?>><summary><span class="step-number"><?= in_array($key,$completed,true)?'✓':array_search($key,array_keys($steps))+1 ?></span><span><?= e($title) ?><small><?= in_array($key,$completed,true)?'Confirmed by you':'Follow the instructions, then mark complete' ?></small></span><span class="step-expand">+</span></summary><div class="step-content">
<?php if($key==='files'): ?>
<p>In txAdmin, open your server’s data folder. Inside <code>resources</code>, create a folder called <code>[avaris]</code> and upload both resource folders you received from your administrator.</p><pre><code>resources/
└── [avaris]/
    ├── Avaris-AC/
    │   ├── fxmanifest.lua
    │   └── config.lua
    └── Avaris-Guard/
        ├── fxmanifest.lua
        └── config.lua</code></pre><p>Keep the folder names exactly as shown. Each fxmanifest.lua must be directly inside its resource folder. The website folder does not belong in your FiveM resources.</p><p class="setup-tip">Don’t have the resources? Ask the person who invited you for Avaris-AC and Avaris-Guard.</p>
<?php elseif($key==='config'): ?>
<p>Open your existing <code>server.cfg</code>. Keep your database and framework dependencies in their existing order. Merge these lines after the framework starts; don’t replace the whole file or duplicate existing ensure lines.</p><div class="snippet-heading"><span>server.cfg / startup</span><button class="button secondary" type="button" data-copy="startup-snippet">Copy configuration</button></div><pre><code id="startup-snippet"><?= e($startup) ?></code></pre>
<p>Leave <code>Config.Framework = 'auto'</code> and <code>Config.AutoProfile.enabled = true</code> in Avaris-AC/config.lua for standard resource names. For a renamed framework core, follow its resource documentation and configure the framework manually.</p>
<?php if($saved['screenshots']): ?><p class="setup-tip">Install screenshot-basic separately before using this startup order. Avaris-AC/data/evidence must exist and be writable.</p><?php endif; ?>
<?php elseif($key==='staff'): ?>
<p>Your website account does not give you FiveM permissions. Find your own <code>license:</code> identifier in your server’s player information. Replace the placeholder below, then add these lines to server.cfg.</p><div class="snippet-heading"><span>server.cfg / trusted staff</span><button class="button secondary" type="button" data-copy="staff-snippet">Copy permissions</button></div><pre><code id="staff-snippet"><?= e($permissions) ?></code></pre><p class="setup-tip">Avaris currently uses avarisac.bypass for its admin commands. This permission also exempts that player from checks. Grant it only to trusted staff; use a separate account without this permission when testing detections.</p>
<?php elseif($key==='diagnostics'): ?>
<p>Restart your server in txAdmin after saving the configuration. Join with your authorized staff account and enter these commands in the in-game chat:</p><div class="command-row"><code>/acsetup</code><span>Check Guard, OneSync, framework discovery and storage.</span></div><div class="command-row"><code>/acstatus</code><span>Confirm the detected framework and resource status.</span></div><div class="command-row"><code>/acpanel</code><span>Open the in-game player-risk and audit panel.</span></div><p>Resolve missing resources or failed required checks before continuing. Optional storage and screenshot checks only need to pass if you use those features.</p><p class="setup-tip">These checks run inside FiveM. This checklist records your confirmation; it does not remotely inspect the server.</p>
<?php elseif($key==='tuning'): ?>
<p>Read the actions in <code>Avaris-AC/config.lua</code> and <code>Avaris-Guard/config.lua</code> before opening your server. Many anomaly checks start in log mode, while some protections enforce immediately.</p><ul class="check-list"><li>Test normal movement, combat, garages and inventory.</li><li>Review /acpanel and the server console for false positives.</li><li>Allow legitimate burst-spawned models before lowering entity limits.</li><li>Use ValidateAction or ExecuteAction inside your own sensitive reward and inventory handlers.</li></ul><p>Change stable detectors to kick or ban only after testing your actual gameplay. Keep your own server-side checks for money, items and permissions.</p>
<?php endif; ?>
<form method="post" class="step-confirm"><?php csrf(); ?><input type="hidden" name="action" value="save_server_step"><input type="hidden" name="step" value="<?= e($key) ?>"><input type="hidden" name="complete" value="<?= in_array($key,$completed,true)?'0':'1' ?>"><button type="submit" class="button <?= in_array($key,$completed,true)?'secondary':'primary' ?>"><?= in_array($key,$completed,true)?'Mark as incomplete':'I’ve done this — save progress' ?></button></form></div></details>
<?php endforeach; ?>
<?php if(count($completed)===5): ?><div class="notice" role="status">All five steps confirmed. Your setup checklist is complete. Keep monitoring real gameplay and revisit any step when your server changes.</div><?php endif; ?>
</div><aside class="setup-help panel"><div class="eyebrow">WHEN SOMETHING DOESN’T WORK</div><h3>Quick fixes.</h3><details><summary>“Resource not found”</summary><p>Check the folder names and remove any extra nested folder created when extracting the archive. Both resources need their own fxmanifest.lua.</p></details><details><summary>Guard is missing</summary><p>Keep Avaris-Guard beside Avaris-AC. Restart Avaris-AC and check the server console for Guard startup errors.</p></details><details><summary>Commands don’t open</summary><p>Check that your license identifier matches the permission line. Restart after saving server.cfg. Website admin rights do not grant in-game command access.</p></details><details><summary>Framework is not detected</summary><p>Start the framework before Avaris-AC. Check its resource name against your selected profile and run /acstatus again.</p></details><details><summary>No screenshots appear</summary><p>Start screenshot-basic before Avaris-AC and check that data/evidence is writable. Evidence capture happens before enforcement, not continuously.</p></details><details><summary>Set up Discord logs</summary><p>Add these private convars to server.cfg, replacing the placeholders locally. Keep webhook URLs private.</p><pre><code>set avarisac_webhook "YOUR_URL"
set avarisac_guard_webhook "YOUR_URL"</code></pre><p>Use set, never setr, for webhook credentials.</p></details><p class="fine-print">Saved <?= e($saved['updated_at']) ?> UTC<br>Progress belongs to your account.</p></aside></div>
<?php endif; endif; ?>
</section>
